version: "2"
sql:
  - engine: "postgresql"
    queries: "../schema/dbqueries/"
    schema: "../schema/migrations/"
    gen:
      go:
        sql_package: "pgx/v5"
        emit_db_tags: true
        package: "generated"
        out: "../internal/repository/generated"
        overrides:
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.Decimal"
            nullable: false
          - db_type: "pg_catalog.numeric"
            go_type: "github.com/shopspring/decimal.NullDecimal"
            nullable: true
